server:
  port: 8080
  host: localhost
  runMode: debug

logger:
  filePath: ../logs/logs.log
  level: debug
  encoding: json

cors:
  allowOrigins: '*'
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: car_sales_db
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: redis
  db: 0
  minIdleConnections: 100
  poolSize: 5000
  poolTimeout: 240
