server:
  port: 8080
  host: 0.0.0.0
  run_mode: debug
logger:
  file_path: ../logs/logs.log
  level: debug
  encoding: json
cors:
  allow_origins: '*'
postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: postgres
  dbname: car_sales_db
  sslmode: disable
redis:
  host: redis_container
  port: 6379
  password: redis
  db: 0
  min_idle_connections: 100
  pool_size: 5000
  pool_timeout: 240
